// <auto-generated />
using CompleteDemo.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompleteDemo.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20191218125156_wwtest")]
    partial class wwtest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("CompleteDemo.Model.ClassInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassExplain")
                        .HasMaxLength(15);

                    b.Property<string>("ClassName")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("classinfo");
                });
#pragma warning restore 612, 618
        }
    }
}
